apiVersion: apps/v1
kind: Deployment
metadata:
  name: dailytrend-deployment
spec:
  selector:
    matchLabels:
      app: dailytrend
  replicas: 1
  template:
    metadata:
      labels:
        app: dailytrend
    spec:
      containers:
      - name: server
        image: IMAGE_URL
        ports:
        - containerPort: 8000
