name: Build docker image and run testcases
on:
  push:
    branches:
      - '!master'
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack and test
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_HOST: "postgres"
          POSTGRES_DB: "postgres"
          REDIS_HOST: "redis-service"
          DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres"
        run: docker-compose run server python manage.py test -v 2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push the api image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: dailytrend
        run: |
          IMAGE_TAG=$(echo ${{ github.sha }} | head -c 7)
          IMAGE_URL=${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
          docker build -t ${IMAGE_URL} .
          docker push ${IMAGE_URL}